-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 23:21:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`battery_capacities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`battery_capacities` (
  `battery_capacity_id` INT NOT NULL,
  `battery_capacity_value` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`battery_capacity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`categories` (
  `categories_id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`diagonals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`diagonals` (
  `diagonal_id` INT NOT NULL,
  `diagonal_value` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`diagonal_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`resolutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`resolutions` (
  `resolution_id` INT NOT NULL,
  `resolution_value` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`resolution_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`flash_memory_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`flash_memory_sizes` (
  `flash_memory_size_id` INT NOT NULL,
  `flash_memory_size_value` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`flash_memory_size_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`colors` (
  `color_id` INT NOT NULL,
  `color_value` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`color_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`display_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`display_types` (
  `display_type_id` INT NOT NULL,
  `display_type_value` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`display_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`memory_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`memory_sizes` (
  `memory_size_id` INT NOT NULL,
  `memory_size_value` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`memory_size_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`cpus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`cpus` (
  `cpu_id` INT NOT NULL,
  `cpu_value` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cpu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`characteristics` (
  `product_id` BIGINT NOT NULL,
  `diagonal_id` INT NULL DEFAULT '0',
  `resolution_id` INT NULL DEFAULT '0',
  `flash_memory_size_id` INT NULL DEFAULT '0',
  `battery_capacity_id` INT NULL DEFAULT '0',
  `color_id` INT NULL DEFAULT '0',
  `display_type_id` INT NULL DEFAULT '0',
  `memory_size_id` INT NULL DEFAULT '0',
  `cpu_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`product_id`),
  INDEX `diagonal_id` (`diagonal_id` ASC) VISIBLE,
  INDEX `resolution_id` (`resolution_id` ASC) VISIBLE,
  INDEX `flash_memory_size_id` (`flash_memory_size_id` ASC) VISIBLE,
  INDEX `battery_capacity_id` (`battery_capacity_id` ASC) VISIBLE,
  INDEX `color_id` (`color_id` ASC) VISIBLE,
  INDEX `display_type_id` (`display_type_id` ASC) VISIBLE,
  INDEX `memory_size_id` (`memory_size_id` ASC) VISIBLE,
  INDEX `cpu_id` (`cpu_id` ASC) VISIBLE,
  CONSTRAINT `characteristics_ibfk_1`
    FOREIGN KEY (`diagonal_id`)
    REFERENCES `webshop`.`diagonals` (`diagonal_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_2`
    FOREIGN KEY (`resolution_id`)
    REFERENCES `webshop`.`resolutions` (`resolution_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_3`
    FOREIGN KEY (`flash_memory_size_id`)
    REFERENCES `webshop`.`flash_memory_sizes` (`flash_memory_size_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_4`
    FOREIGN KEY (`battery_capacity_id`)
    REFERENCES `webshop`.`battery_capacities` (`battery_capacity_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_5`
    FOREIGN KEY (`color_id`)
    REFERENCES `webshop`.`colors` (`color_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_6`
    FOREIGN KEY (`display_type_id`)
    REFERENCES `webshop`.`display_types` (`display_type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_7`
    FOREIGN KEY (`memory_size_id`)
    REFERENCES `webshop`.`memory_sizes` (`memory_size_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `characteristics_ibfk_8`
    FOREIGN KEY (`cpu_id`)
    REFERENCES `webshop`.`cpus` (`cpu_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `active` BIT(1) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`manufacturers` (
  `manufacturers_id` BIGINT NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`manufacturers_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`products` (
  `product_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `image_name` VARCHAR(100) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `manufacturer_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `manufacturer_id` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `webshop`.`categories` (`categories_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `webshop`.`manufacturers` (`manufacturers_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`grade` (
  `product_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `grade` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `grade_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `webshop`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `webshop`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`orders` (
  `orders_id` VARCHAR(200) NOT NULL,
  `time_of_order_creation` DATETIME NOT NULL,
  `status` ENUM('accepted', 'confirmed', 'generated', 'sent', 'completed', 'canceled') NULL DEFAULT NULL,
  `status_details` VARCHAR(200) NULL DEFAULT NULL,
  `address` VARCHAR(200) NOT NULL,
  `payment_type` VARCHAR(200) NOT NULL,
  `card_number` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `webshop`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`product_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`product_orders` (
  `product_orders_id` BIGINT NOT NULL AUTO_INCREMENT,
  `orders_id` VARCHAR(200) NOT NULL,
  `product_id` BIGINT NOT NULL,
  `total_price` DECIMAL(10,0) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_orders_id`),
  INDEX `orders_id` (`orders_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_orders_ibfk_1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `webshop`.`orders` (`orders_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_orders_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `webshop`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `webshop`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`roles` (
  `role_id` BIGINT NOT NULL,
  `role` VARCHAR(5) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
